# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# mastodon = Mammal.create(
#     common_name: "American mastodon",
#     url: "https://en.wikipedia.org/wiki/American_mastodon",
#     kingdom: "Animalia",
#     phylum: "Chordata",
#     scientific_class: "Mammalia",
#     order: "Proboscidea",
#     family: "Mammutidae",
#     genus: "Mammut",
#     species: "M. americanum",
#     description: "A mastodon (Greek: breast and tooth) is any proboscidean belonging to the extinct genus Mammut (family Mammutidae) that inhabited North and Central America during the late Miocene or late Pliocene up to their extinction at the end of the Pleistocene 10,000 to 11,000 years ago. Mastodons lived in herds and were predominantly forest-dwelling animals that lived on a mixed diet obtained by browsing and grazing, somewhat similar to their distant relatives, modern elephants, but probably with greater emphasis on browsing.",
#     extinction_date_BCE: "8500",
#     range: "North America"
# )

mammals_array = [
    {
        common_name: "American mountain deer",
        url: "https://en.wikipedia.org/wiki/American_mountain_deer",
        kingdom: "Animalia",
        phylum: "Chordata",
        scientific_class: "Mammalia",
        order: "Artiodactyla",
        family: "Cervidae",
        genus: "Odocoileus",
        species: "Odocoileus lucasi",
        description: "Odocoileus lucasi (historically Navahoceros fricki), known commonly as the American mountain deer, is an extinct species of North American deer.",
        extinction_date_BCE: "10000",
        range: "the Rocky Mountains, the Guadalupe Mountains"
    },
    {
        common_name: "American lion",
        url: "https://en.wikipedia.org/wiki/American_lion",
        kingdom: "Animalia",
        phylum: "Chordata",
        scientific_class: "Mammalia",
        order: "Carnivora",
        family: "Felidae",
        genus: "Panthera",
        species: "P. atrox",
        description: "The American lion (Panthera atrox), also known as the North American lion, or American cave lion, is an extinct pantherine cat that lived in North America during the Pleistocene epoch and the early Holocene epoch, about 340,000 to 11,000 years ago. Its fossils have been excavated from Alaska to Mexico. Genetic analysis has shown that the American lion and the Late Pleistocene Eurasian cave lion (Panthera spelaea) are sister lineages. It was about 25% larger than the modern lion, making it one of the largest known felids.",
        extinction_date_BCE: "11000",
        range: "Alaska to Central America"
    },
    {
        common_name: "Aztlanolagus agilis",
        url: "https://en.wikipedia.org/wiki/Aztlanolagus",
        kingdom: "Animalia",
        phylum: "Chordata",
        scientific_class: "Mammalia",
        order: "Lagomorpha",
        family: "Leporidae",
        genus: "Aztlanolagus ",
        species: "A. agilis",
        description: "Aztlanolagus is an extinct monotypic genus of rabbit that lived during the Quaternary in what is now the Southern to Southwestern United States and northern Mexico. Aztlanolagus agilis is currently the only recognized species, though differences among recovered fossils suggest that there may have been other species. The generic name refers to the legendary place of origin of the Nahua peoples as recorded in the mythological accounts of the Aztecs and other Nahua groups. By some traditions, this legendary locale is placed in the border regions of the Southwestern United States and adjacent northern Mexico.",
        extinction_date_BCE: "10000",
        range: "southeastern Arizona to Central America"
    },
    {
        common_name: "Beautiful armadillo",
        url: "https://en.wikipedia.org/wiki/Dasypus_bellus",
        kingdom: "Animalia",
        phylum: "Chordata",
        scientific_class: "Mammalia",
        order: "Cingulata",
        family: "Dasypodidae",
        genus: "Dasypus",
        species: "D. bellus",
        description: "Dasypus bellus, the beautiful armadillo, is an extinct armadillo species endemic to North America and South America from the Pleistocene, living from 1.8 mya 11,000 years ago, existing for approximately 1.789 million years.",
        extinction_date_BCE: "8000",
        range: "the North American Southwest to South America"
    },
    {
        common_name: "Bison antiquus",
        url: "https://en.wikipedia.org/wiki/Bison_antiquus",
        kingdom: "Animalia",
        phylum: "Chordata",
        scientific_class: "Mammalia",
        order: "Artiodactyla",
        family: "Bovidae",
        genus: "Bison",
        species: "Bison antiquus",
        description: "Bison antiquus, the antique or ancient bison, is an extinct species of bison that lived in Late Pleistocene North America until around 10,000 years ago. It was one of the most common large herbivores on the North American continent during the late Pleistocene, and is a direct ancestor of the living American bison along with Bison occidentalis.",
        extinction_date_BCE: "10000",
        range: "the U.S. and Canada"
    },
    {
        common_name: "Bison occidentalis",
        url: "https://en.wikipedia.org/wiki/Bison_occidentalis",
        kingdom: "Animalia",
        phylum: "Chordata",
        scientific_class: "Mammalia",
        order: "Artiodactyla",
        family: "Bovidae",
        genus: "Bison",
        species: "Bison occidentalis",
        description: "Bison occidentalis is an extinct species of bison that lived in North America, and potentially in Siberia and the Japanese archipelago from about 11,000 to 5,000 years ago, spanning the end of the Pleistocene to the mid-Holocene.",
        extinction_date_BCE: "3000",
        range: "Alaska to Minnesota"
    },
    {
        common_name: "Camelops",
        url: "https://en.wikipedia.org/wiki/Camelops",
        kingdom: "Animalia",
        phylum: "Chordata",
        scientific_class: "Mammalia",
        order: "Artiodactyla",
        family: "Camelidae",
        genus: "Camelops ",
        species: "Camelops kansanus.",
        description: "Camelops is an extinct genus of camels that lived in Western North America, ranging from Alaska to Mexico, from the middle Pliocene to the end of the Pleistocene. It is more closely related to the Old World dromedary and Bactrian camel than the New World alpaca, guanaco, llama, and vicuÃ, making it a true camel of the Camelini tribe. Its name is derived from the Ancient Greek (camelos, camel) and (face), i.e. camel-face",
        extinction_date_BCE: "8000",
        range: "Western North America"
    },
    {
        common_name: "Caribbean ground sloths",
        url: "https://en.wikipedia.org/wiki/Pilosans_of_the_Caribbean",
        kingdom: "Animalia  ??",
        phylum: "Chordata  ??",
        scientific_class: "Mammalia  ??",
        order: "Pilosa",
        family: "Megalocnidae ",
        genus: "??",
        species: "??",
        description: " The mammalian order Pilosa, which includes the sloths and anteaters, includes various species from the Caribbean region. Many species of sloths are known from the Greater Antilles, all of which became extinct over the last millennia, but some sloths and anteaters survive on islands closer to the mainland.",
        extinction_date_BCE: "3000",
        range: "the Caribbean islands"
    },
    {
        common_name: "Columbian mammoth",
        url: "https://en.wikipedia.org/wiki/Columbian_mammoth",
        kingdom: "Animalia",
        phylum: "Chordata",
        scientific_class: "Mammalia",
        order: "Proboscidea",
        family: "Elephantidae",
        genus: "Mammuthus",
        species: "M. columbi ",
        description: "The Columbian mammoth (Mammuthus columbi) is an extinct species of mammoth that inhabited North America as far north as the northern United States and as far south as Costa Rica during the Pleistocene epoch. It was one of the last in a line of mammoth species, beginning with Mammuthus subplanifrons in the early Pliocene. The Columbian mammoth evolved from the steppe mammoth, which entered North America from Asia about 1.5 million years ago. The pygmy mammoths of the Channel Islands of California evolved from Columbian mammoths. The closest extant relative of the Columbian and other mammoths is the Asian elephant.",
        extinction_date_BCE: "5800",
        range: "the northern U.S. to Central America"
    },
    {
        common_name: "Dire wolf",
        url: "https://en.wikipedia.org/wiki/Dire_wolf",
        kingdom: "Animalia",
        phylum: "Chordata",
        scientific_class: "Mammalia",
        order: "Carnivora",
        family: "Canidae",
        genus: "Canis",
        species: "C. dirus",
        description: "Reaching 4m (13ft) at the shoulders and 10 tonnes (22,000lb) in weight, the Columbian mammoth was one of the largest species of mammoth. It had long, curved tusks and four molars, which were replaced six times during the lifetime of an individual. It most likely used its tusks and trunk like modern elephants for manipulating objects, fighting, and foraging. Bones, hair, dung, and stomach contents have been discovered, but no preserved carcasses are known. The Columbian mammoth preferred open areas, such as parkland landscapes, and fed on sedges, grasses, and other plants",
        extinction_date_BCE: "7400",
        range: "mid-latitude North America to South America"
    },
    {
        common_name: "Florida spectacled bear",
        url: "https://en.wikipedia.org/wiki/Tremarctos_floridanus",
        kingdom: "Animalia",
        phylum: "Chordata",
        scientific_class: "Mammalia",
        order: "Carnivora",
        family: "Ursidae",
        genus: "Tremarctos",
        species: "T. floridanus",
        description: "Tremarctos floridanus, occasionally called the Florida spectacled bear, Florida cave bear, or rarely Florida short-faced bear, is an extinct species of bear in the family Ursidae, subfamily Tremarctinae. T. floridanus was endemic to North America from the Pliocene to the end of the Pleistocene epoch (12,000 years ago), existing for approximately 4.9 million years.",
        extinction_date_BCE: "8000",
        range: "the southern U.S."
    },
    {
        common_name: "Glyptodon",
        url: "https://en.wikipedia.org/wiki/Glyptodon",
        kingdom: "Animalia",
        phylum: "Chordata",
        scientific_class: "Mammalia",
        order: "Cingulata",
        family: "Chlamyphoridae",
        genus: "Glyptodon ",
        species: "G. clavipes Owen ",
        description: "Glyptodon (from Greek for grooved or carved tooth) was a genus of large, heavily armored mammals of the subfamily Glyptodontinae (glyptodonts or glyptodontines)  relatives of armadillos that lived during the Pleistocene epoch. It was roughly the same size and weight as a Volkswagen Beetle. With its rounded, bony shell and squat limbs, it superficially resembled a turtle, and the much earlier dinosaurian ankylosaur  providing an example of the convergent evolution of unrelated lineages into similar forms. In 2016 an analysis of Doedicurus mtDNA found it was, in fact, nested within the modern armadillos as the sister group of a clade consisting of Chlamyphorinae and Tolypeutinae. For this reason, glyptodonts and all armadillos but Dasypus were relocated to a new family, Chlamyphoridae, and glyptodonts were demoted from the former family Glyptodontidae to a subfamily.",
        extinction_date_BCE: "10000",
        range: "Central America to South America"
    },
    {
        common_name: "Harlan's muskox",
        url: "https://en.wikipedia.org/wiki/Bootherium_bombifrons",
        kingdom: "Animalia",
        phylum: "Chordata",
        scientific_class: "Mammalia",
        order: "Artiodactyla",
        family: "Bovidae",
        genus: "Bootherium ",
        species: "Bootherium bombifrons",
        description: "Bootherium is an extinct bovid genus from the middle to late Pleistocene of North America which contains a single species, Bootherium bombifrons. Vernacular names for Bootherium include Harlan's muskox, woodox, woodland muskox, helmeted muskox, or bonnet-headed muskox. Bootherium was one of the most widely distributed muskox species in North America during the Pleistocene era. It is most closely related to the modern muskox, from which it diverged around 3 million years ago, it is possibly synonymous with Euceratherium, although this is uncertain.",
        extinction_date_BCE: "9000",
        range: "North America"
    },
    {
        common_name: "Holmesina septentrionalis",
        url: "https://en.wikipedia.org/wiki/Holmesina",
        kingdom: "Animalia",
        phylum: "Chordata",
        scientific_class: "Mammalia",
        order: "Cingulata",
        family: "Pampatheriidae",
        genus: "Holmesina",
        species: "H. septentrionalis ",
        description: "Holmesina is a genus of pampathere, an extinct group of armadillo-like creatures that were distantly related to extant armadillos. Like armadillos, and unlike the other extinct branch of megafaunal cingulates, the glyptodonts, the shell was made up of flexible plates which allowed the animal to move more easily. Holmesina species were herbivores that grazed on coarse vegetation; armadillos are mostly insectivorous or omnivorous.",
        extinction_date_BCE: "8000",
        range: "the southern U.S. to South America"
    },
    {
        common_name: "Jefferson's ground sloth",
        url: "https://en.wikipedia.org/wiki/Megalonyx",
        kingdom: "Animalia",
        phylum: "Chordata",
        scientific_class: "Mammalia",
        order: "Pilosa",
        family: "Megalonychidae",
        genus: "Megalonyx",
        species: "M. jeffersonii ",
        description: "Megalonyx (Greek, large claw) is an extinct genus of ground sloths of the family Megalonychidae, native to North America during Pleistocene epoch. It became extinct during the Quaternary extinction event at the end of the Rancholabrean of the Pleistocene, living from ~2.4 Mya 11,000 years ago. The type species, M. jeffersonii, measured about 3 meters (9.8 ft) and weighed up to 1,000 kilograms (2,200 lb). Megalonyx is descended from Pliometanastes, a genus of ground sloth that had arrived in North America during the Late Miocene, prior to the Great American Biotic Interchange. Megalonyx had the widest distribution of any North American ground sloth, having a range encompassing most of the contiguous United States, extending as far North as Alaska during warm periods.",
        extinction_date_BCE: "11000",
        range: "North America"
    },
    {
        common_name: "Mylohyus",
        url: "https://en.wikipedia.org/wiki/Mylohyus",
        kingdom: "Animalia",
        phylum: "Chordata",
        scientific_class: "Mammalia",
        order: "Artiodactyla",
        family: "Tayassuidae",
        genus: "Mylohyus",
        species: "M. elmorei",
        description: "Mylohyus is an extinct genus of peccary found in North and Central America. It evolved in the Pliocene and its extinction is probably as recent as 9,000 years ago. It would have been familiar with early humans.",
        extinction_date_BCE: "9000",
        range: "North America"
    },
    {
        common_name: "Pleistocene North American jaguar",
        url: "https://en.wikipedia.org/wiki/Panthera_onca_augusta",
        kingdom: "Animalia",
        phylum: "Chordata",
        scientific_class: "Mammalia",
        order: "Carnivora",
        family: "Felidae",
        genus: "Panthera",
        species: "P. onca",
        description: "Panthera onca augusta, commonly known as the Pleistocene jaguar or simply the giant jaguar, is an extinct subspecies of the jaguar that was endemic to North America during the Pleistocene epoch (1.8 mya11,000 years ago).",
        extinction_date_BCE: "10000",
        range: "the Pacific Northwest to Panama"
    },
    {
        common_name: "Pygmy mammoth",
        url: "https://en.wikipedia.org/wiki/Pygmy_mammoth",
        kingdom: "Animalia",
        phylum: "Chordata",
        scientific_class: "Mammalia",
        order: "Proboscidea",
        family: "Elephantidae",
        genus: "Mammuthus",
        species: "M. exilis ",
        description: "The pygmy mammoth or Channel Islands mammoth (Mammuthus exilis) is an extinct species of dwarf elephant descended from the Columbian mammoth (M. columbi) of mainland North America. This species became extinct during the Quaternary extinction event in which many megafauna species became extinct due to changing conditions to which the species could not adapt. A case of island or insular dwarfism, from a recent analysis in 2010 it was determined that M. exilis was on average, 1.72 m (5.6 ft) tall at the shoulders and 760 kg (1,680 lb) in weight, in stark contrast to its 4.3 m (14 ft) tall, 9,070 kg (20,000 lb) ancestor. Another estimate gives a shoulder height of 2.02 m (6.6 ft) and a weight of 1,350 kg (2,980 lb).",
        extinction_date_BCE: "10,800-11,300",
        range: "the Channel Islands of California, U.S."
    },
    {
        common_name: "Saber-toothed cat",
        url: "https://en.wikipedia.org/wiki/Smilodon",
        kingdom: "Animalia",
        phylum: "Chordata",
        scientific_class: "Mammalia",
        order: "Carnivora",
        family: "Felidae",
        genus: "Smilodon",
        species: "Simlodon populator",
        description: "Smilodon is a genus of the extinct machairodont subfamily of the felids. It is one of the most famous prehistoric mammals and the best known saber-toothed cat. Although commonly known as the saber-toothed tiger, it was not closely related to the tiger or other modern cats. Smilodon lived in the Americas during the Pleistocene epoch (2.5mya 10,000 years ago). The genus was named in 1842 based on fossils from Brazil; the generic name means scalpel or two-edged knife combined with tooth. Overall, Smilodon was more robustly built than any extant cat, with particularly well-developed forelimbs and exceptionally long upper canine teeth. Its jaw had a bigger gape than that of modern cats, and its upper canines were slender and fragile, being adapted for precision killing.",
        extinction_date_BCE: "8000",
        range: "North America"
    },
    {
        common_name: "Scimitar-toothed cats",
        url: "https://en.wikipedia.org/wiki/Homotherium",
        kingdom: "Animalia",
        phylum: "Chordata",
        scientific_class: "Mammalia",
        order: "Carnivora",
        family: "Felidae",
        genus: "Homotherium",
        species: "Homotherium latidens ",
        description: "Homotherium (also known as the scimitar-toothed cat or scimitar cat) is an extinct genus of machairodontine saber-toothed cats, often termed scimitar-toothed cats, that inhabited North America, South America, Eurasia, and Africa during the Pliocene and Pleistocene epochs (4 mya 12,000 years ago), existing for approximately 4 million years. It became extinct in Africa some 1.5 million years ago. The most recent Eurasian remains, recovered from what is now the North Sea, have been dated to around 28,000 years BP. In South America it is only known from a few remains in the northern region (Venezuela), from the mid-Pleistocene.",
        extinction_date_BCE: "10000",
        range: "North America"
    },
    {
        common_name: "Giant short-faced bear",
        url: "https://en.wikipedia.org/wiki/Short-faced_bear",
        kingdom: "Animalia",
        phylum: "Chordata",
        scientific_class: "Mammalia",
        order: "Carnivora",
        family: "Ursidae",
        genus: "Arctodus",
        species: "Arctodus pristinus ",
        description: "The short-faced bear (Arctodus sp.) is an extinct bear genus that inhabited North America during the Pleistocene epoch from about 1.8 Mya until 11,000 years ago. It was the most common early North American bear and was most abundant in California. There are two recognized species: the lesser short-faced bear (Arctodus pristinus) and the giant short-faced bear (Arctodus simus), with the latter considered to be one of the largest known terrestrial mammalian carnivores that has ever existed. It has been hypothesized that their extinction coincides with the Younger Dryas period of global cooling commencing around 10,900 BC.",
        extinction_date_BCE: "8000",
        range: "North America"
    },
    {
        common_name: "Shrub-ox",
        url: "https://en.wikipedia.org/wiki/Shrub-ox",
        kingdom: "Animalia",
        phylum: "Chordata",
        scientific_class: "Mammalia",
        order: "Artiodactyla",
        family: "Bovidae",
        genus: "Euceratherium ",
        species: "Euceratherium collinum",
        description: "The shrub-ox (Euceratherium collinum) is an extinct genus and species of ovibovine caprine native to North America along with Bootherium (Bootherium bombifrons) and Soergel's ox (Soergelia mayfieldi).",
        extinction_date_BCE: "9500",
        range: "North America"
    },
    {
        common_name: "Steppe bison",
        url: "https://en.wikipedia.org/wiki/Steppe_bison",
        kingdom: "Animalia",
        phylum: "Chordata",
        scientific_class: "Mammalia",
        order: "Artiodactyla",
        family: "Bovidae",
        genus: "Bison",
        species: "Bison priscus",
        description: "The steppe bison or steppe wisent (Bison priscus) is an extinct species of bison that was once found on the mammoth steppe where its range included British Isles, Europe, Central Asia, Northern to Northeastern Asia, Beringia, and North America, from northwest Canada to Mexico during the Quaternary. This wide distribution is sometimes called the Pleistocene bison belt compared to the Great bison belt. The radiocarbon dating of a steppe bison skeleton indicates that it was present 5,400 years ago in Alaska. Three chronological subspecies, Bison priscus priscus, Bison priscus mediator, and Bison priscus gigas, have been suggested.",
        extinction_date_BCE: "5400",
        range: "North America"
    },
    {
        common_name: "Stout-legged llama",
        url: "https://en.wikipedia.org/wiki/Paleolama",
        kingdom: "Animalia",
        phylum: "Chordata",
        scientific_class: "Mammalia",
        order: "Artiodactyla",
        family: "Camelidae",
        genus: "Palaeolama",
        species: "Palaeolama weddeli ",
        description: "Palaeolama (lit. 'ancient llama') is an extinct genus of laminoid camelid that existed from the Late Pliocene to the Early Holocene (1.8 to 0.011 Ma). Its range extended from North America to the intertropical region of South America.",
        extinction_date_BCE: "10000",
        range: "North and South America"
    },
    {
        common_name: "Western horse",
        url: "https://en.wikipedia.org/wiki/Equus_occidentalis",
        kingdom: "Animalia",
        phylum: "Chordata",
        scientific_class: "Mammalia",
        order: "Perissodactyla",
        family: "Equidae",
        genus: "Equus",
        species: "E.occidentalis ",
        description: "Equus occidentalis or the Western horse, was a Pleistocene species of horse, now extinct, that inhabited North America. This species represents the larger end of the prehistoric horse spectrum it was about the size of a mustang, weighing up to 519 kilograms (1,144 lb). It was a stoutly built animal and resembled the extinct quagga or the modern plains zebra, although it was not a close relative to either of these.",
        extinction_date_BCE: "10000",
        range: "North America"
    },
    {
        common_name: "Woolly mammoth",
        url: "https://en.wikipedia.org/wiki/Woolly_mammoth",
        kingdom: "Animalia",
        phylum: "Chordata",
        scientific_class: "Mammalia",
        order: "Proboscidea",
        family: "Elephantidae",
        genus: "Mammuthus",
        species: "M.primigenius ",
        description: "The woolly mammoth (Mammuthus primigenius) is a species of mammoth that lived during the Pleistocene until its extinction in the Holocene epoch. It was one of the last in a line of mammoth species, beginning with Mammuthus subplanifrons in the early Pliocene. The woolly mammoth began to diverge from the steppe mammoth about 800,000 years ago in East Asia. Its closest extant relative is the Asian elephant. The appearance and behaviour of this species are among the best studied of any prehistoric animal because of the discovery of frozen carcasses in Siberia and Alaska, as well as skeletons, teeth, stomach contents, dung, and depiction from life in prehistoric cave paintings. Mammoth remains had long been known in Asia before they became known to Europeans in the 17th century. The origin of these remains was long a matter of debate, and often explained as being remains of legendary creatures. The mammoth was identified as an extinct species of elephant by Georges Cuvier in 1796.",
        extinction_date_BCE: "2000",
        range: "Wrangel Island (the Bering Sea)"
    }
]

mammals_array.each do |mammal| 
# byebug
    Mammal.create(mammal)
end
